config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('service.urls', namespace='service')),
    path('admin/', admin.site.urls),
    path('info/', include('core.urls', namespace='info')),
]

urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('contact/', views.ContactDetail, name='ContactDetail'),
    path('help_messenger/', views.step_help_messenger_detail, name='step_help_messenger_detail'),
]

service/urls.py
from django.urls import path

from . import views

app_name = 'service'
urlpatterns = [
    path('', views.ServiceList.as_view(), name='index'),
    path('service/<int:pk>', views.ServiceDetail.as_view(), name='ServicesDetail'),
]

services/urls.py
from django.urls import path

from . import views

app_name = 'services'
urlpatterns = [
    path('', views.ServiceList.as_view(), name='index'),
    path('service/<int:pk>', views.ServiceDetail.as_view(), name='ServicesDetail'),
]

core/models.py
from django.db import models


# Storage information about company
class Contact(models.Model):
    name = models.CharField(
        max_length=100
    )
    address_shop = models.CharField(
        max_length=100
    )
    email = models.CharField(
        max_length=100
    )
    telephone = models.CharField(
        max_length=100
    )

    img_logo = models.ImageField(
        upload_to='../media_root',
        null=True,
        blank=True,
    )

    def __str__(self):
        return '{}'.format(self.name)


class StepHelpMessenger(models.Model):

    TYPE_HELP_CHOICES = [
        ("TM", "Telegram"),
        ("VB", "Viber"),
    ]

    help_choices = models.CharField(
        max_length=2,
        choices=TYPE_HELP_CHOICES,
        default="TM",
    )
    # for i in TypeHelpMessenger.get_all_names(TypeHelpMessenger):
    #    print(i)

    description_stage = models.TextField(
        blank=True,
    )

    img_step = models.ImageField(
        upload_to='../media_root',
        null=True,
        blank=True,
    )

    # Get url img. This is safe way
    @property
    def img_url(self):
        if self.img_step and hasattr(self.img_step, 'url'):
            return self.img_step.url


class TypeHelpMessenger(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True
    )
    description_name = models.TextField(
        blank=True,
    )
    steps = models.ManyToManyField(StepHelpMessenger, related_name='steps', blank=True,)

    # def get_all_names(self):
    #    list = []
    #    for i in TypeHelpMessenger.objects.all():
    #        list.append(i.name)
    #    return list

service/models.py
from django.db import models


# Storage images for services. Many to many
class ImageService(models.Model):
    name = models.CharField(max_length=100, default = "Имя картинки")
    img = models.ImageField(
        upload_to='../media_root',
        null=True,
        blank=True,
    )

    descriptions = models.TextField()

    # Get url img. This is safe way
    @property
    def img_url(self):
        if self.img and hasattr(self.img, 'url'):
            return self.img.url


# Storage requirements for services. Many to many
class ServiceRequirement(models.Model):
    requirement = models.TextField()


# Storage information about services
class Service(models.Model):
    # name services
    name = models.CharField(
        max_length=100
    )
    # images for list services
    img_title = models.ImageField(
        upload_to='../media_root',
        null=True
    )
    # images for detail services
    img_service = models.ManyToManyField(ImageService, related_name='img_serv')
    # description service
    description = models.TextField()
    # requirements service
    list_requirements = models.ManyToManyField(ServiceRequirement, related_name='layout_requirements',
                                               blank=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        ordering = ('name', 'description')

services/models.py
from django.db import models

# Create your models here.

from django.db import models

"""
class Parameters_service(models.Model):
    name = models.CharField(
        max_length=400
    )
    descriptions = models.CharField(
        max_length=400
    )
"""

class Image_service(models.Model):
    img = models.ImageField(
        upload_to='../media_root',
        null=True,
        blank=True,
    )
    descriptions = models.TextField()


class Service(models.Model):
    name = models.CharField(
        max_length=100
    )

    img_title = models.ImageField(
        upload_to='../media_root',
        null=True,
        blank=True,
    )

    img_services = models.ManyToManyField(Image_service, related_name='img_serv')

    descriptions = models.TextField()

    def __str__(self):
        return '{}'.format(self.name)

core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from core.models import (
    Contact, TypeHelpMessenger
)
from service.models import Service
from django.views.generic import (
    ListView, DetailView
)


def ContactDetail(request):
    contact = Contact.objects.get(id=1)
    context = {
        'contact': contact,
        'service_menu': Service.objects.all(),

    }
    return render(request, 'core/contact_detail.html', context)


# View help messenger
def step_help_messenger_detail(request):
    contact = Contact.objects.get(id=1)
    context = {
        'contact': contact,
        'service_menu': Service.objects.all(),
        'type_help_messenger': TypeHelpMessenger.objects.all(),
        'type_help_telegram': TypeHelpMessenger.objects.get(name="Telegram"),
        'type_help_viber': TypeHelpMessenger.objects.get(name="Viber"),

    }
    return render(request, 'core/help_messenger.html', context)

service/views.py
from django.shortcuts import render

from .models import Service
from django.views.generic import (
    ListView, DetailView
)
from core.models import Contact


# View services on the main page
class ServiceList(ListView):
    model = Service
    context_object_name = 'service_list'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get information about company
        context['contact'] = Contact.objects.get(id=1)
        context['service_menu'] = Service.objects.all()
        return context


# View information for services
class ServiceDetail(DetailView):
    model = Service
    context_object_name = 'service_detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get information about company
        context['contact'] = Contact.objects.get(id=1)
        # Get all list for menubar
        context['service_menu'] = Service.objects.all()
        return context

core/templates/core/contact_detail.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Контакты {% endblock %}
{% block body %}
<div class="row ">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'service:index'%}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Контакты</li>

       </ol>
</nav>
        </div>
<div class="row align-items-center ">
<h3>Контакты </h3>
            </div>
<!--Google map-->
<div class="row g-4 md-4 mt-1 mb-1 justify-content-center">
    <div class="col-sm justify-content-center ">
        <div class="map-container" >
            <iframe src="https://maps.google.com/maps?q=Полтавский+Шлях%2C+56%2F58&rlz=1C1CHZN_ruUA958UA958&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
                style="border:0" allowfullscreen></iframe>
        </div>
    </div>
    <div class="col-sm-6 mx-auto contact-detail-info blockquote headings-line-height justify-content-center">
        <p> Телефон: <br> {{contact.telephone}}</p>
        <p> Адрес: <br> {{contact.email}}</p>
        <p> Почта: <br> {{contact.address_shop}}</p>
        <p> Режим работы: <br>  пн - пт 8-00 до 18-00 <br> вс. выходной</p>
    </div>
</div>
{% endblock%}

core/templates/core/help_messenger.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Помощь{% endblock %}
{% block body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'service:index'%}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Помощь</li>

       </ol>
</nav>
    <div class="row ">
        <h3>Помощь</h3>
    </div>
    <div class="row ">
        <p> Some text </p>
    </div>
    <div class="row ">
        <h4>Оглавление </h4>
    </div>
    <ol>
        {%for type in type_help_messenger%}
            <div class="row">
                <li> {{type.name}}</li>
            </div>
        {% endfor %}
    </ol>
    {%for type in type_help_messenger%}
        <div class="row">
            <h3>Помощь с Telegram</h3>
        </div>
        <div class="row">
            <p>{{ type_help_telegram.description_name }}</p>
        </div>
        <div class="row">
            <h4>Шаги</h4>
        </div>
            <ol>
                {%for steps in type_help_telegram.steps.all%}
                    <div class="row">
                        <li>
                            <p>{{steps.description_stage}}</p>
                            <img src="{% with 'core'|add:steps.img_url as image_static %}
                            {% static image_static %}
                            {% endwith %}" class="img-thumbnail" alt="img_step">
                        </li>
                    </div>
                {% endfor %}
            </ol>
    {% endfor %}
{% endblock%}

service/templates/service/service_detail.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Услуга {{object.name}} {% endblock %}
{% block body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'service:index'%}">Главная</a></li>
    <li class="breadcrumb-item active" aria-current="page">Услуга {{object.name}}</li>
       </ol>
</nav>

<h3>Услуга {{object.name}} </h3>

<section class="gallery">
    <div class="row ">
        {%for img in object.img_service.all%}
            <div class="col">
                <img src="{% with 'core'|add:img.img_url as image_static %}
                        {% static image_static %}
                        {% endwith %}" class="gallery-item" alt="gallery">
           </div>
        {% endfor %}
    </div>
</section>
<div class="modal fade" id="gallery-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <img src="" class="modal-img" alt="modal img">
      </div>
    </div>
  </div>
</div>
{%if object.list_requirements.all.exists%}
<div class="row ">
    <h4>Требования к макетам </h4>
</div>
<div class="row list_requirements">
    {%for list_item in object.list_requirements.all%}
        <li>{{list_item.requirement|safe}}</li>
    {% empty %}
    <!-- not -->
    {% endfor %}

</div>
{%endif%}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/detail_service.js' %}"></script>

{% endblock%}

service/templates/service/service_list.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Список услуг {% endblock %}
{% block body %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item active">Главная</li>
       </ol>
</nav>
    <h3>Список услуг </h3>
<div class="row row-cols-1 row-cols-md-4 g-4 md-4 mt-1 mb-1">
    {% for service in object_list %}
            <div class="col-xs-3 align-self-center list_services ">
             <a href="{% url 'service:ServicesDetail' pk=service.id%}">
                <div class="card " style="width: 18rem; ">
                     <img style="height: 10rem;"  src="
                        {% with 'core'|add:service.img_title.url as image_static %}
                        {% static image_static %}
                        {% endwith %}"
                        class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{service.name}}</h5>
                        <!--
                        <p class="card-text">
                        {{service.description}} </p>
                        <a href="{% url 'service:ServicesDetail' pk=service.id%}" class="btn btn-primary">Детальный просмотр</a>
                        -->
                    </div>

                </div>
                    </a>
            </div>
    {% endfor %}
        </div>
    <nav>
<ul class="pagination">
                <li class="page-item">
                <a href="?page=1" class="page-link">
                    Первая страница
                </a>
            </li>
    {% if page_obj.has_previous %}
      <li  class="page-item" ><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class=" page-item disabled"></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class=" page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% else %}
        <li  class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li  class="page-item" ><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class=" page-item disabled"></li>
    {% endif %}
    <li class="page-item">
                <a href="?page=last" class="page-link">
                    Последняя страница
                </a>
            </li>
  </ul>

    </nav>
{% endblock%}

services/templates/services/service_list.html
{% extends 'base\main.html' %}
{% load static %}
{% block title %} Main {% endblock %}
{% block body %}
<div class="row row-cols-1 row-cols-md-4 g-4 md-4 mt-1 mb-1">
    {% for service in object_list %}
            <div class="col align-self-center ">
                <div class="card" style="width: 18rem;">
                     <img src="
                        {% with 'core'|add:service.img_title.url as image_static %}
                        {% static image_static %}
                        {% endwith %}"
                        class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{service.name}}</h5>
                        <p class="card-text">
                        {{service.descriptions}} </p>
                        <a href="{% url 'services:ServicesDetail' pk=service.id%}" class="btn btn-primary">Детальный просмотр</a>
                    </div>

                </div>

            </div>
    {% endfor %}
        </div>
    <nav>
<ul class="pagination">
                <li class="page-item">
                <a href="?page=1" class="page-link">
                    Первая страница
                </a>
            </li>
    {% if page_obj.has_previous %}
      <li  class="page-item" ><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class=" page-item disabled"></li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class=" page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% else %}
        <li  class="page-item" ><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li  class="page-item" ><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class=" page-item disabled"></li>
    {% endif %}
    <li class="page-item">
                <a href="?page=last" class="page-link">
                    Последняя страница
                </a>
            </li>
  </ul>

    </nav>
    </div>
</div>
{% endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <script src="https://kit.fontawesome.com/332010db09.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %} " type="text/css">
    <link rel="stylesheet" href="{% static 'css/main_head.css' %} " type="text/css">
    <title>
        {% block title %} {% endblock %}
    </title>
  </head>
<body>
<header>
  <div class="container mt-1 fs-5 ">
    <div class="row align-items-center  ">
        <div class="col-sm-2 d-none d-lg-block d-print-block ">
            <img src="
                {% with 'core'|add:contact.img_logo.url as image_static %}
                {% static image_static %}
                {% endwith %}"  class=" img-fluid" alt="home" />
        </div>
        <div class="col-sm-2">
            <p> Адрес: <br>
                {{contact.address_shop}}
        </div>
        <div class="col-sm-3">
            <p> Почта: <br>
            {{contact.email}} </p>
        </div>
        <div class="col">
            <i class="fab fa-viber"> {{contact.telephone}}</i>
            <br>
            <i class="fab fa-telegram"> {{contact.telephone}}</i>
        </div>
        <div class="col-sm-3 " >
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </nav>
        </div>
    </div>
  <div class="row">
      <div class="col-1 p-2" >
        <div class="btn-group-vertical" role="group" aria-label="Button group with nested dropdown">
            <button type="button" class="btn btn-primary">fdfdfdfdfdffdfdfdfrereter</button>
            <button type="button" class="btn btn-primary">2</button>
            <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
            </button>
            <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li><a class="dropdown-item" href="1">Dropdown link</a></li>
                <li><a class="dropdown-item" href="2">Dropdown link</a></li>
            </ul>
        </div>
    </div>
  </div>
</header>
    {% block main %}
   {% endblock %}
<!-- Footer -->
<footer class="text-center text-lg-start text-muted bg-light">
  <!-- Section: Links  -->
    <div class="container text-center text-md-start">
      <!-- Grid row -->
      <div class="row mt-4  p-1">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>  {{contact.name}}
          </h6>
          <p>
            Полиграфические услуги в Харькове
          </p>
        </div>
          <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset"></a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Контакты
          </h6>
          <p><i class="fas fa-home me-3"></i> {{contact.address_shop}}</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            {{contact.email}}
          </p>
          <p><i class="fab fa-viber me-3"></i> {{contact.telephone}}</p>
          <p><i class="fab fa-telegram me-3"></i> {{contact.telephone}}</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright: Все права защищены. При использовании материалов
сайта прямая гиперссылка на сайт zrada.com.ua
обязательна.
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>

templates/base/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/fontawesome.js' %}" ></script>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %} " type="text/css">
    <link rel="stylesheet" href="{% static 'css/main_head.css' %} " type="text/css">
    <link rel="stylesheet" href="{% static 'css/detail_service.css' %} " type="text/css">
    <link rel="stylesheet" href="{% static 'css/contact_detail.css' %} " type="text/css">
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
    {% block main %}
   {% endblock %}
</body>
</html>

templates/base/header.html
{% extends 'base/head.html' %}
{% load static %}
{% block main %}
<header>
  <div class="container mt-1 fs-5 px-md-0">
    <div class="row align-items-center  ">
        <div class="col-sm-2 d-none d-lg-block d-print-block ">
            <a  href="{% url 'service:index' %}">
            <img src="
                {% with 'core'|add:contact.img_logo.url as image_static %}
                {% static image_static %}
                {% endwith %}"  class=" img-fluid" alt="home" />
            </a>
        </div>
        <div class="col-sm-2">
            <p> Адрес: <br>
                {{contact.address_shop}}
        </div>
        <div class="col-sm">
            <p> Почта: <br>
            {{contact.email}} </p>
        </div>
        <div class="col">
            <i class="fab fa-viber"> </i>  {{contact.telephone}}
            <br>
            <i class="fab fa-telegram"></i> {{contact.telephone}}
        </div>
        <div class="col-sm-3" >
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </nav>
        </div>
    </div>
  <div class="row">
      <div class="col-1 p-2" >

    </div>
  </div>
</header>
<div class="container px-3 px-md-0">
    <div class="row ">
         <div class="col-sm-2">
                <div class="btn-group" role="group" >
                    <a href="{% url 'service:index' %}" class="btn btn-primary">Главная  </a>
                    <a href="{% url 'info:ContactDetail' %}" class="btn btn-primary"> Контакты </a>
                    <a href="{% url 'info:step_help_messenger_detail' %}" class="btn btn-primary"> Помощь</a>
                </div>
         </div>
    </div>
    <br>
        <div class="col-xs-3 text-center">
        <div class="btn-group nav " role="group">
                {% for service in service_menu %}
                    <a href="{% url 'service:ServicesDetail' pk=service.id%}" class="btn btn-primary">
                            <div class="text-decoration-none text-reset" >
                                {{service.name}}
                            </div>
                    </a>
            {% endfor %}
        </div>
    </div>


    {% block footer %}
    {% endblock %}
{% endblock %}

templates/base/main.html
{% extends 'base/header.html' %}
{% load static %}

{% block header %}
{% block footer %}


    {% block body %}

    {% endblock %}
  </div>

<!-- Footer -->
<footer class="text-center text-lg-start text-muted bg-light">
    <div class="container text-center text-md-start">
      <div class="row mt-4  p-1">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
           <!-- <i class="fas fa-gem me-3"></i> --> {{contact.name}}
          </h6>
          <p>
            Полиграфические услуги в Харькове
          </p>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Контакты
          </h6>
          <p><i class="fas fa-home me-3"></i> {{contact.address_shop}}</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            {{contact.email}}
          </p>
          <p><i class="fab fa-viber me-3"></i> {{contact.telephone}}</p>
          <p><i class="fab fa-telegram me-3"></i> {{contact.telephone}}</p>
        </div>
      </div>
    </div>

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright: Все права защищены. При использовании материалов
сайта прямая гиперссылка на сайт zrada.com.ua
обязательна.
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    {% endblock %}

{% endblock%}